/***********************************************
* GENERATED BY ZEBBLE
***********************************************/

#region UI.Pages.Page1
namespace UI.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using Domain;
    using Zebble;
    using Zebble.Plugin;

    public partial class Page1 : Zebble.Page
    {
        protected override async Task InitializeFromMarkup()
        {
            await base.InitializeFromMarkup();

            var __textView1 = new TextView { Id = "__textView1", Text = "Hello World!" }
            .Set(x => x.Style.Margin.Top(100));

            await Add(__textView1);
        }
    }
}
#endregion

namespace UI
{
    partial class StartUp
    {
        // Hashed content of all resources
        public override string GetResourcesVersion() => "EidilPGR2bW11gkXlcaJhtQy91Y";
    }
}
