/***********************************************
* GENERATED BY ZEBBLE
***********************************************/

using System;
using Zebble;
using Zebble.Services;
using Zebble.Plugin;
using UI.Modules;
using UI.Pages;
using UI.Templates;
using System.Threading.Tasks;

namespace UI
{
    public class CssStyles
    {
        public static void LoadAll()
        {
            // ======================================================================
            // App.UI\Styles\Android.css---------------------------------------------

            if (CssEngine.Platform == DevicePlatform.Android)
            {
                CssEngine.Add(new File_App.UI.Styles.Android.TextInputCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TextViewCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.ButtonCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.IconButtonCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.IconButtonTextViewCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.PopUpDialogCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.PopUpPageCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.ModuleHeaderTitleCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.NavigationBarTitleCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TextInput_1CssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.ListViewCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.ListViewListViewItemCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.ListViewListViewItemImageViewViewRowCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TabsCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TabsTabsTabCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TabsTabsTabActiveCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TabsTabsTabLabelCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.TabsTabsTabIconCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.SwitchCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.SwitchBarCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.SwitchToggleCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.SwitchCheckedToggleCssRule());
                CssEngine.Add(new File_App.UI.Styles.Android.SwitchCheckedBarCssRule());
            }

            // ======================================================================
            // App.UI\Styles\iOS.css-------------------------------------------------

            if (CssEngine.Platform == DevicePlatform.IOS)
            {
                CssEngine.Add(new File_App.UI.Styles.IOS.TextInputCssRule());
                CssEngine.Add(new File_App.UI.Styles.IOS.TextViewCssRule());
                CssEngine.Add(new File_App.UI.Styles.IOS.ModuleHeaderTitleCssRule());
                CssEngine.Add(new File_App.UI.Styles.IOS.DialogCssRule());
                CssEngine.Add(new File_App.UI.Styles.IOS.PrimaryButtonCssRule());
            }

            // ======================================================================
            // App.UI\Styles\Windows.css---------------------------------------------

            if (CssEngine.Platform == DevicePlatform.Windows)
            {
                CssEngine.Add(new File_App.UI.Styles.Windows.TextViewCssRule());
                CssEngine.Add(new File_App.UI.Styles.Windows.TextInputCssRule());
                CssEngine.Add(new File_App.UI.Styles.Windows.ModuleHeaderTitleCssRule());
            }

            // ======================================================================
            // App.UI\Styles\_Core.css-----------------------------------------------
            CssEngine.Add(new File_App.UI.Styles.Core.TextInputCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ButtonCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.CheckBoxCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.CheckBoxCheckedCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.CheckBoxCheckedImageCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.IconButtonCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.IconButtonTextViewCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.IconButtonIconCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SearchInputIconCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SearchInputTextBoxCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SearchInputCancelButtonCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SearchInputFocusTextBoxCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SearchInputFocusCancelButtonCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SwitchCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SwitchBarCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.SwitchToggleCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.FormFieldCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.FormFieldLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.FormFieldIconCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.DialogCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.DialogTitleCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.DialogButtonsRowCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PromptDescriptionCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PromptInputCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.AlertDialogMessageCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PopUpCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PopupOverlayCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.WaitingOverlayCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.WaitingOverlay_1CssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ToastCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ToastOKButtonCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ToastLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.GridEmptyTextLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ListViewEmptyTextLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ListViewItemCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.ListViewLazyLoadedOptionsListOptionCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.NavBarPageCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.NavBarPageBodyScrollerCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.NavBarPageBodyScrollerBodyCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.NavigationBarCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.NavigationBarTitleCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.WaitingIndicatorCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.WaitingIndicatorImageViewCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.RefreshingIndicatorCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TabsCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TabsTabsTabCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TabsTabsTabIconCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TabsTabsTabLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.DatePickerCellCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TimePickerCellCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.DatePickerCellLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TimePickerCellLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.DatePickerDialogRotatorsRowCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.TimePickerDialogRotatorsRowCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PickerCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PickerLabelCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PickerCaretCssRule());
            CssEngine.Add(new File_App.UI.Styles.Core.PickerPlaceholderLabelCssRule());
        }
    }
}

// Ensure auto-generated namespaces exist:
namespace UI.Modules { }
namespace UI.Pages { }
namespace UI.Templates { }
namespace Zebble.Plugin { }
namespace Zebble.Data { }

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "TextInput")]
    [CssBody("font-family: Roboto;")]
    class TextInputCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextInput

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextInput)untypedView;
            view.Css.Font.Name = "Roboto";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "TextView")]
    [CssBody("font-family: Roboto;")]
    class TextViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextView

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextView)untypedView;
            view.Css.Font.Name = "Roboto";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Button")]
    [CssBody("text-transform: uppercase; height: 36px; border-radius: 4px;")]
    class ButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Button

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Button)untypedView;
            view.Css.Height = 36;
            view.Css.TextTransform = TextTransform.Uppercase;
            view.Css.Border.Radius = 4;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "IconButton")]
    [CssBody("text-transform: uppercase; height: 36px; border-radius: 4px;")]
    class IconButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: IconButton

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (IconButton)untypedView;
            view.Css.Height = 36;
            view.Css.TextTransform = TextTransform.Uppercase;
            view.Css.Border.Radius = 4;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "IconButton #TextView")]
    [CssBody("text-transform: uppercase;")]
    class IconButtonTextViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #TextView

            view = CssEngine.FindParentByType<IconButton>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.TextTransform = TextTransform.Uppercase;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "PopUp Dialog")]
    [CssBody("border-radius: 4px;")]
    class PopUpDialogCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Dialog

            view = CssEngine.FindParentByType<PopUp>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Dialog)untypedView;
            view.Css.Border.Radius = 4;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "PopUp Page")]
    [CssBody("border-radius: 4px;")]
    class PopUpPageCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Page

            view = CssEngine.FindParentByType<PopUp>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Page)untypedView;
            view.Css.Border.Radius = 4;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", ".module-header-title")]
    [CssBody("font-size: 24px;")]
    class ModuleHeaderTitleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: .module-header-title

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Font.Size = 24;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "NavigationBar #Title")]
    [CssBody("text-align: left; padding-left: 65px; font-size: 20px; font-weight: normal;")]
    class NavigationBarTitleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Title

            view = CssEngine.FindParentByType<NavigationBar>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Font.Size = 20;
            view.Css.Font.Bold = false;
            view.Css.Padding.Left = 65;
            view.Css.TextAlignment = Alignment.Left;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "TextInput")]
    [CssBody("font-family: Roboto; border: 0 #e6e6e6; border-bottom-width: 1px; padding: 2px; margin-bottom: 10px;")]
    class TextInput_1CssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextInput

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextInput)untypedView;
            view.Css.Font.Name = "Roboto";
            view.Css.Padding(2);
            view.Css.Margin.Bottom = 10;
            view.Css.Border = new Border(0, "#e6e6e6");
            view.Css.Border.Bottom = 1;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "ListView")]
    [CssBody("padding-top: 8px;")]
    class ListViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: ListView

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (ListView)untypedView;
            view.Css.Padding.Top = 8;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "ListView ListViewItem")]
    [CssBody("height: 72px; padding-left: 10px; padding-right: 10px;")]
    class ListViewListViewItemCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: ListViewItem

            view = CssEngine.FindParentByType<ListView>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (ListViewItem)untypedView;
            view.Css.Height = 72;
            view.Css.Padding.Left = 10;
            view.Css.Padding.Right = 10;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "ListView ListViewItem ImageView.view-row")]
    [CssBody("display: none;")]
    class ListViewListViewItemImageViewViewRowCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            if (!(view is ImageView && HasClass(view, "view-row"))) return false;

            view = CssEngine.FindParentByType<ListViewItem>(view);

            if (view == null) return false;

            view = CssEngine.FindParentByType<ListView>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (ImageView)untypedView;
            view.Css.Ignored = true;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Tabs")]
    [CssBody("height: auto;")]
    class TabsCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Tabs

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Tabs)untypedView;
            view.Css.Height = null;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Tabs Tabs-Tab")]
    [CssBody("border: 0 #43aaa9; font-size: 14px; margin-bottom: 1px; height: 40px;")]
    class TabsTabsTabCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Tabs-Tab

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Tabs.Tab)untypedView;
            view.Css.Height = 40;
            view.Css.Font.Size = 14;
            view.Css.Margin.Bottom = 1;
            view.Css.Border = new Border(0, "#43aaa9");

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Tabs Tabs-Tab:active")]
    [CssBody("background-color: transparent; border-bottom-width: 2px;")]
    class TabsTabsTabActiveCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            if (!(view is Tabs.Tab && view.PseudoCssState.ContainsWholeWord("active"))) return false;

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Tabs.Tab)untypedView;
            view.Css.BackgroundColor = Colors.Transparent;
            view.Css.Border.Bottom = 2;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Tabs Tabs-Tab #Label")]
    [CssBody("text-transform: uppercase; height: 100%; vertical-align: middle;")]
    class TabsTabsTabLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = CssEngine.FindParentByType<Tabs.Tab>(view);

            if (view == null) return false;

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.TextTransform = TextTransform.Uppercase;
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Tabs Tabs-Tab #Icon")]
    [CssBody("display: none;")]
    class TabsTabsTabIconCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Icon

            view = CssEngine.FindParentByType<Tabs.Tab>(view);

            if (view == null) return false;

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Ignored = true;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Switch")]
    [CssBody("width: 50px;")]
    class SwitchCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Switch

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Switch)untypedView;
            view.Css.Width = 50;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Switch #Bar")]
    [CssBody("background: #C8C8C8; height: 14px; border-radius: 7px; margin-top: 6px; opacity: 1;")]
    class SwitchBarCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Bar

            view = CssEngine.FindParentByType<Switch>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 14;
            view.Css.Margin.Top = 6;
            view.Css.BackgroundColor = "#C8C8C8";
            view.Css.Border.Radius = 7;
            view.Css.Opacity = 1;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Switch #Toggle")]
    [CssBody("background: white; border-width: 1px; border-color: #C8C8C8; margin: 0;")]
    class SwitchToggleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Toggle

            view = CssEngine.FindParentByType<Switch>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Margin(0);
            view.Css.BackgroundColor = Colors.White;
            view.Css.Border.Width = 1;
            view.Css.Border.Color = "#C8C8C8";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Switch:checked #Toggle")]
    [CssBody("background: #43aaa9; border-color: transparent;")]
    class SwitchCheckedToggleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Toggle

            view = view.parent;
            while (true)
            {
                if (view == null) return false;
                else if (view is Switch && view.PseudoCssState.ContainsWholeWord("checked")) break;
                view = view.parent;
            }

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.BackgroundColor = "#43aaa9";
            view.Css.Border.Color = Colors.Transparent;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Android
{
    [CssSelector(DevicePlatform.Android, "Styles\\Android.css", "Switch:checked #Bar")]
    [CssBody("opacity: 0.35; background: #43aaa9;")]
    class SwitchCheckedBarCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Bar

            view = view.parent;
            while (true)
            {
                if (view == null) return false;
                else if (view is Switch && view.PseudoCssState.ContainsWholeWord("checked")) break;
                view = view.parent;
            }

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Opacity = 0.35f;
            view.Css.BackgroundColor = "#43aaa9";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.IOS
{
    [CssSelector(DevicePlatform.IOS, "Styles\\iOS.css", "TextInput")]
    [CssBody("font-family: Arial;")]
    class TextInputCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextInput

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextInput)untypedView;
            view.Css.Font.Name = "Arial";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.IOS
{
    [CssSelector(DevicePlatform.IOS, "Styles\\iOS.css", "TextView")]
    [CssBody("font-family: Arial;")]
    class TextViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextView

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextView)untypedView;
            view.Css.Font.Name = "Arial";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.IOS
{
    [CssSelector(DevicePlatform.IOS, "Styles\\iOS.css", ".module-header-title")]
    [CssBody("font-size: 24px; font-weight: bold;")]
    class ModuleHeaderTitleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: .module-header-title

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Font.Size = 24;
            view.Css.Font.Bold = true;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.IOS
{
    [CssSelector(DevicePlatform.IOS, "Styles\\iOS.css", "Dialog")]
    [CssBody("border-radius: 15px;")]
    class DialogCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Dialog

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Dialog)untypedView;
            view.Css.Border.Radius = 15;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.IOS
{
    [CssSelector(DevicePlatform.IOS, "Styles\\iOS.css", ".primary-button")]
    [CssBody("border-radius: 5px;")]
    class PrimaryButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: .primary-button

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Border.Radius = 5;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Windows
{
    [CssSelector(DevicePlatform.Windows, "Styles\\Windows.css", "TextView")]
    [CssBody("font-family: \"Segoe UI\";")]
    class TextViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextView

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextView)untypedView;
            view.Css.Font.Name = "Segoe UI";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Windows
{
    [CssSelector(DevicePlatform.Windows, "Styles\\Windows.css", "TextInput")]
    [CssBody("font-family: \"Segoe UI\";")]
    class TextInputCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextInput

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextInput)untypedView;
            view.Css.Font.Name = "Segoe UI";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Windows
{
    [CssSelector(DevicePlatform.Windows, "Styles\\Windows.css", ".module-header-title")]
    [CssBody("font-size: 40px;")]
    class ModuleHeaderTitleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: .module-header-title

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Font.Size = 40;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "TextInput")]
    [CssBody("padding: 7px; border: 1px solid #eee;")]
    class TextInputCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TextInput

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TextInput)untypedView;
            view.Css.Padding(7);
            view.Css.Border = new Border(1, "#eee");

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Button")]
    [CssBody("padding: 5px;")]
    class ButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Button

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Button)untypedView;
            view.Css.Padding(5);

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "CheckBox")]
    [CssBody("width: 24px; height: 24px; border: 1px solid #aaaaaa; border-radius: 12px; background: transparent;")]
    class CheckBoxCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: CheckBox

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (CheckBox)untypedView;
            view.Css.Height = 24;
            view.Css.Width = 24;
            view.Css.Border = new Border(1, "#aaaaaa");
            view.Css.Border.Radius = 12;
            view.Css.BackgroundColor = Colors.Transparent;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "CheckBox:checked")]
    [CssBody("background-color: black;")]
    class CheckBoxCheckedCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            if (!(view is CheckBox && view.PseudoCssState.ContainsWholeWord("checked"))) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (CheckBox)untypedView;
            view.Css.BackgroundColor = Colors.Black;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "CheckBox > #CheckedImage")]
    [CssBody("width: 100%; height: 100%; background-image: url(Images/Icons/Check.png); background-size: contain; padding: 5px;")]
    class CheckBoxCheckedImageCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #CheckedImage

            view = view.parent;

            if (view == null) return false;
            else if (!(view is CheckBox)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.BackgroundImageStretch = Stretch.Fit;
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Padding(5);
            view.Css.BackgroundImagePath = "Images/Icons/Check.png";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "IconButton")]
    [CssBody("margin: 2px; height: 40px; padding: 5px;")]
    class IconButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: IconButton

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (IconButton)untypedView;
            view.Css.Height = 40;
            view.Css.Padding(5);
            view.Css.Margin(2);

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "IconButton > #TextView")]
    [CssBody("text-align: center; height: 100%;")]
    class IconButtonTextViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #TextView

            view = view.parent;

            if (view == null) return false;
            else if (!(view is IconButton)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "IconButton > #Icon")]
    [CssBody("height: 20px; background-position: left; background-size: contain; margin-top: 5px; margin-left: 5px;")]
    class IconButtonIconCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Icon

            view = view.parent;

            if (view == null) return false;
            else if (!(view is IconButton)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.BackgroundImageStretch = Stretch.Fit;
            view.Css.Height = 20;
            view.Css.Margin.Top = 5;
            view.Css.Margin.Left = 5;
            view.Css.BackgroundImageAlignment = Alignment.Left;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "SearchInput > #Icon")]
    [CssBody("background-image: url(Images/Icons/Search.png); opacity: 0.3; padding: 8px;")]
    class SearchInputIconCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Icon

            view = view.parent;

            if (view == null) return false;
            else if (!(view is SearchInput)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Padding(8);
            view.Css.Opacity = 0.3f;
            view.Css.BackgroundImagePath = "Images/Icons/Search.png";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "SearchInput > #TextBox")]
    [CssBody("text-align: center;")]
    class SearchInputTextBoxCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #TextBox

            view = view.parent;

            if (view == null) return false;
            else if (!(view is SearchInput)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "SearchInput > #CancelButton")]
    [CssBody("border: 0; height: 35px; left: 100%; white-space: nowrap; padding: 0; padding-left: 0; opacity: 0;")]
    class SearchInputCancelButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #CancelButton

            view = view.parent;

            if (view == null) return false;
            else if (!(view is SearchInput)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 35;
            view.Css.Padding(0);
            view.Css.Padding.Left = 0;
            view.Css.Border = 0;
            view.Css.X = 100.Percent();
            view.Css.WrapText = false;
            view.Css.Opacity = 0;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "SearchInput:focus > #TextBox")]
    [CssBody("text-align: left; padding-left: 30px;")]
    class SearchInputFocusTextBoxCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #TextBox

            view = view.parent;

            if (view == null) return false;
            else if (!(view is SearchInput && view.PseudoCssState.ContainsWholeWord("focus"))) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Padding.Left = 30;
            view.Css.TextAlignment = Alignment.Left;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "SearchInput:focus > #CancelButton")]
    [CssBody("opacity: 1;")]
    class SearchInputFocusCancelButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #CancelButton

            view = view.parent;

            if (view == null) return false;
            else if (!(view is SearchInput && view.PseudoCssState.ContainsWholeWord("focus"))) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Opacity = 1;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Switch")]
    [CssBody("width: 56px; height: 32px;")]
    class SwitchCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Switch

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Switch)untypedView;
            view.Css.Height = 32;
            view.Css.Width = 56;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Switch #Bar")]
    [CssBody("height: 32px; border-radius: 16px;")]
    class SwitchBarCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Bar

            view = CssEngine.FindParentByType<Switch>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 32;
            view.Css.Border.Radius = 16;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Switch #Toggle")]
    [CssBody("height: 28px; width: 28px; border-radius: 14px; background: white; margin: 2px;")]
    class SwitchToggleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Toggle

            view = CssEngine.FindParentByType<Switch>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 28;
            view.Css.Width = 28;
            view.Css.Margin(2);
            view.Css.Border.Radius = 14;
            view.Css.BackgroundColor = Colors.White;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "FormField")]
    [CssBody("margin-top: 5px;")]
    class FormFieldCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: FormField

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (FormField)untypedView;
            view.Css.Margin.Top = 5;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "FormField > #Label")]
    [CssBody("width: 30%; height: 100%;")]
    class FormFieldLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = view.parent;

            if (view == null) return false;
            else if (!(view is FormField)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.Width = 30.Percent();

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "FormField > #Icon")]
    [CssBody("width: 30%; width: 25px; height: 25px;")]
    class FormFieldIconCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Icon

            view = view.parent;

            if (view == null) return false;
            else if (!(view is FormField)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 25;
            view.Css.Width = 30.Percent();
            view.Css.Width = 25;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Dialog")]
    [CssBody("background: white; padding: 15px;")]
    class DialogCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Dialog

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Dialog)untypedView;
            view.Css.Padding(15);
            view.Css.BackgroundColor = Colors.White;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Dialog > #Title")]
    [CssBody("text-align: center; font-size: 16px; margin-bottom: 10px; font-weight: bold;")]
    class DialogTitleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Title

            view = view.parent;

            if (view == null) return false;
            else if (!(view is Dialog)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Font.Size = 16;
            view.Css.Font.Bold = true;
            view.Css.Margin.Bottom = 10;
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Dialog > #ButtonsRow")]
    [CssBody("margin-top: 30px;")]
    class DialogButtonsRowCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #ButtonsRow

            view = view.parent;

            if (view == null) return false;
            else if (!(view is Dialog)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Margin.Top = 30;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Prompt #Description")]
    [CssBody("white-space: pre-wrap;")]
    class PromptDescriptionCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Description

            view = CssEngine.FindParentByType<Prompt>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.WrapText = true;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Prompt #Input")]
    [CssBody("margin-top: 10px; margin-bottom: 10px;")]
    class PromptInputCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Input

            view = CssEngine.FindParentByType<Prompt>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Margin.Top = 10;
            view.Css.Margin.Bottom = 10;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "AlertDialog #Message")]
    [CssBody("text-align: center; margin-top: 10px;")]
    class AlertDialogMessageCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Message

            view = CssEngine.FindParentByType<AlertDialog>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Margin.Top = 10;
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "PopUp")]
    [CssBody("width: 100%; height: 100%; padding: 0 20px;")]
    class PopUpCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: PopUp

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (PopUp)untypedView;
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Padding(vertical: 0, horizontal: 20);

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "#PopupOverlay")]
    [CssBody("width: 100%; height: 100%; position: absolute; opacity: 0.35; background: black;")]
    class PopupOverlayCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #PopupOverlay

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Absolute = true;
            view.Css.Opacity = 0.35f;
            view.Css.BackgroundColor = Colors.Black;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "#WaitingOverlay")]
    [CssBody("width: 100%; height: 100%; position: absolute; opacity: 0.35; background: black;")]
    class WaitingOverlayCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #WaitingOverlay

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Absolute = true;
            view.Css.Opacity = 0.35f;
            view.Css.BackgroundColor = Colors.Black;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "#WaitingOverlay")]
    [CssBody("opacity: 0.15;")]
    class WaitingOverlay_1CssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #WaitingOverlay

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Opacity = 0.15f;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Toast")]
    [CssBody("background: black; border-radius: 7px; margin: 20px; padding: 20px;")]
    class ToastCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Toast

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Toast)untypedView;
            view.Css.Padding(20);
            view.Css.Margin(20);
            view.Css.BackgroundColor = Colors.Black;
            view.Css.Border.Radius = 7;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Toast #OKButton")]
    [CssBody("height: auto; width: 50px;")]
    class ToastOKButtonCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #OKButton

            view = CssEngine.FindParentByType<Toast>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = null;
            view.Css.Width = 50;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Toast #Label")]
    [CssBody("color: #fff;")]
    class ToastLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = CssEngine.FindParentByType<Toast>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.TextColor = "#fff";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Grid > #EmptyTextLabel")]
    [CssBody("text-align: center;")]
    class GridEmptyTextLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #EmptyTextLabel

            view = view.parent;

            if (view == null) return false;
            else if (!(view is Grid)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "ListView > #EmptyTextLabel")]
    [CssBody("text-align: center;")]
    class ListViewEmptyTextLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #EmptyTextLabel

            view = view.parent;

            if (view == null) return false;
            else if (!(view is ListView)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "ListViewItem")]
    [CssBody("border-top: 1px;")]
    class ListViewItemCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: ListViewItem

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (ListViewItem)untypedView;
            view.Css.Border.Top = 1;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "ListView:lazy-loaded OptionsList-Option")]
    [CssBody("height: 30px;")]
    class ListViewLazyLoadedOptionsListOptionCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: OptionsList-Option

            view = view.parent;
            while (true)
            {
                if (view == null) return false;
                else if (view is ListView && view.PseudoCssState.ContainsWholeWord("lazy-loaded")) break;
                view = view.parent;
            }

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (OptionsList.Option)untypedView;
            view.Css.Height = 30;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "NavBarPage")]
    [CssBody("height: 100%; width: 100%;")]
    class NavBarPageCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: NavBarPage

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (NavBarPage)untypedView;
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "NavBarPage > #BodyScroller")]
    [CssBody("background: white;")]
    class NavBarPageBodyScrollerCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #BodyScroller

            view = view.parent;

            if (view == null) return false;
            else if (!(view is NavBarPage)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.BackgroundColor = Colors.White;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "NavBarPage > #BodyScroller > #Body")]
    [CssBody("padding: 10px;")]
    class NavBarPageBodyScrollerBodyCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Body

            view = view.parent;

            if (view == null) return false;
            else if (!(view.Id == "BodyScroller")) return false;

            view = view.parent;

            if (view == null) return false;
            else if (!(view is NavBarPage)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Padding(10);

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "NavigationBar")]
    [CssBody("height: 64px; padding: 10px;")]
    class NavigationBarCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: NavigationBar

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (NavigationBar)untypedView;
            view.Css.Height = 64;
            view.Css.Padding(10);

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "NavigationBar > #Title")]
    [CssBody("font-size: 18px; font-weight: bold; text-align: center; width: 100%; height: 100%;")]
    class NavigationBarTitleCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Title

            view = view.parent;

            if (view == null) return false;
            else if (!(view is NavigationBar)) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Font.Size = 18;
            view.Css.Font.Bold = true;
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Waiting-Indicator")]
    [CssBody("height: 60px; border-radius: 30px;")]
    class WaitingIndicatorCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Waiting-Indicator

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Waiting.Indicator)untypedView;
            view.Css.Height = 60;
            view.Css.Border.Radius = 30;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Waiting-Indicator ImageView")]
    [CssBody("height: 100%;")]
    class WaitingIndicatorImageViewCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: ImageView

            view = CssEngine.FindParentByType<Waiting.Indicator>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (ImageView)untypedView;
            view.Css.Height = 100.Percent();

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "#RefreshingIndicator")]
    [CssBody("width: 50px; height: 50px; background: url(Images/Icons/Spinner.png);")]
    class RefreshingIndicatorCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #RefreshingIndicator

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 50;
            view.Css.Width = 50;
            view.Css.BackgroundImagePath = "Images/Icons/Spinner.png";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Tabs")]
    [CssBody("background: #444444; height: 54px;")]
    class TabsCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Tabs

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Tabs)untypedView;
            view.Css.Height = 54;
            view.Css.BackgroundColor = "#444444";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Tabs Tabs-Tab")]
    [CssBody("padding-top: 9px; padding-bottom: 9px;")]
    class TabsTabsTabCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Tabs-Tab

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Tabs.Tab)untypedView;
            view.Css.Padding.Top = 9;
            view.Css.Padding.Bottom = 9;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Tabs Tabs-Tab #Icon")]
    [CssBody("background-position: center; height: 22px; width: 100%;")]
    class TabsTabsTabIconCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Icon

            view = CssEngine.FindParentByType<Tabs.Tab>(view);

            if (view == null) return false;

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 22;
            view.Css.Width = 100.Percent();
            view.Css.BackgroundImageAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Tabs Tabs-Tab #Label")]
    [CssBody("font-size: 11px; color: #eeeeee; width: 100%; text-align: center;")]
    class TabsTabsTabLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = CssEngine.FindParentByType<Tabs.Tab>(view);

            if (view == null) return false;

            view = CssEngine.FindParentByType<Tabs>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Width = 100.Percent();
            view.Css.Font.Size = 11;
            view.Css.TextColor = "#eeeeee";
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "DatePicker-Cell")]
    [CssBody("height: 50px; width: 100%;")]
    class DatePickerCellCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: DatePicker-Cell

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (DatePicker.Cell)untypedView;
            view.Css.Height = 50;
            view.Css.Width = 100.Percent();

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "TimePicker-Cell")]
    [CssBody("height: 50px; width: 100%;")]
    class TimePickerCellCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: TimePicker-Cell

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (TimePicker.Cell)untypedView;
            view.Css.Height = 50;
            view.Css.Width = 100.Percent();

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "DatePicker-Cell #Label")]
    [CssBody("height: 100%; width: 100%; text-align: center; font-size: 16px;")]
    class DatePickerCellLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = CssEngine.FindParentByType<DatePicker.Cell>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Font.Size = 16;
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "TimePicker-Cell #Label")]
    [CssBody("height: 100%; width: 100%; text-align: center; font-size: 16px;")]
    class TimePickerCellLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = CssEngine.FindParentByType<TimePicker.Cell>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.Width = 100.Percent();
            view.Css.Font.Size = 16;
            view.Css.TextAlignment = Alignment.Middle;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "DatePicker-Dialog #RotatorsRow")]
    [CssBody("margin-top: 15px;")]
    class DatePickerDialogRotatorsRowCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #RotatorsRow

            view = CssEngine.FindParentByType<DatePicker.Dialog>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Margin.Top = 15;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "TimePicker-Dialog #RotatorsRow")]
    [CssBody("margin-top: 15px;")]
    class TimePickerDialogRotatorsRowCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #RotatorsRow

            view = CssEngine.FindParentByType<TimePicker.Dialog>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Margin.Top = 15;

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Picker")]
    [CssBody("padding: 7px; border: 1px solid #eee;")]
    class PickerCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: Picker

            return true;
        }

        public override Task Apply(View untypedView)
        {
            var view = (Picker)untypedView;
            view.Css.Padding(7);
            view.Css.Border = new Border(1, "#eee");

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Picker #Label")]
    [CssBody("height: 100%;")]
    class PickerLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Label

            view = CssEngine.FindParentByType<Picker>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Picker #Caret")]
    [CssBody("background: url(Images/Icons/Caret.png); width: 20px;")]
    class PickerCaretCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #Caret

            view = CssEngine.FindParentByType<Picker>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Width = 20;
            view.Css.BackgroundImagePath = "Images/Icons/Caret.png";

            return Task.CompletedTask;
        }
    }
}

namespace File_App.UI.Styles.Core
{
    [CssSelector("Styles\\_Core.css", "Picker #PlaceholderLabel")]
    [CssBody("color: #ddd; height: 100%;")]
    class PickerPlaceholderLabelCssRule : CssRule
    {
        public override bool Matches(View view)
        {
            // CssEngine will only call me if a view matches: #PlaceholderLabel

            view = CssEngine.FindParentByType<Picker>(view);

            if (view == null) return false;

            return true;
        }

        public override Task Apply(View view)
        {
            view.Css.Height = 100.Percent();
            view.Css.TextColor = "#ddd";

            return Task.CompletedTask;
        }
    }
}